/*
 * This source file was generated by the Gradle 'init' task
 */
package chat;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // Test eliminado: la clase App ahora es un @SpringBootApplication
}
